version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgresDB
    environment:
      - JWT_KEY=YOUR_JWT_KEY
      - POSTGRE_URI_PRD=postgresql+psycopg2://postgres:postgres@postgresDB:5432/postgres
  
  postgresDB:
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
